package com.games.nuvei.enums;

import lombok.Getter;

@Getter
public enum PaymentGWErrorCode {
    INVALID_EXPIRATION_DATE(1001, "Invalid Expiration Date"),
    EXPIRATION_DATE_TOO_OLD(1002, "Expiration Date Too Old"),
    INVALID_CARD_NUMBER_ALPHA_NUMERIC(1101, "Invalid Card Number (Alpha Numeric)"),
    INVALID_CARD_NUMBER_DIGITS_COUNT(1102, "Invalid Card Number (Digits Count)"),
    INVALID_CARD_NUMBER_MOD10(1103, "Invalid Card Number (MOD 10)"),
    INVALID_CVV2(1104, "Invalid CVV2"),
    AUTH_CODE_MISMATCH(1105, "Auth Code/Trans ID/Credit Card Number Mismatch"),
    CREDIT_AMOUNT_EXCEED_TOTAL(1106, "Credit Amount Exceed Total Charges"),
    CANNOT_CREDIT_THIS_CC(1107, "Cannot Credit this CC company"),
    ILLEGAL_INTERVAL_AUTH_FORCE(1108, "Illegal interval between auth and force"),
    NOT_ALLOWED_CC_COMPANY(1109, "Not allowed to process this CC company"),
    UNRECOGNIZED_CC_COMPANY(1110, "Unrecognized credit card company"),
    TRANSACTION_CHARGEBACK(1111, "This Transaction was charged back"),
    SALE_ALREADY_CREDITED(1112, "Sale/Settle was already credited"),
    TERMINAL_NOT_READY(1113, "Terminal is not ready for this credit card company"),
    BLACKLISTED_CARD(1114, "Black listed card number"),
    ILLEGAL_BIN(1115, "Illegal BIN number"),
    CUSTOM_FRAUD_FILTER(1116, "<Custom Fraud Screen Filter>"),
    CVV2_REPLY_INVALID(1118, "'N' Cannot be a Positive CVV2 Reply"),
    AVS_REPLY_INVALID(1119, "'B'/'N' Cannot be a Positive AVS Reply"),
    INVALID_AVS(1120, "Invalid AVS"),
    CVV2_NOT_ALLOWED(1121, "CVV2 check is not allowed in Credit/Settle/Void"),
    AVS_NOT_ALLOWED(1122, "AVS check is not allowed in Credit/Settle/Void"),
    CREDIT_EXCEEDS_RESTRICTION(1124, "Credits total amount exceeds restriction"),
    FORMAT_ERROR(1125, "Format Error"),
    CREDIT_EXCEEDS_CEILING(1126, "Credit amount exceeds ceiling"),
    LIMIT_EXCEEDING_AMOUNT(1127, "Limit exceeding amount"),
    INVALID_TXN_TYPE_CODE(1128, "Invalid Transaction Type Code"),
    GENERAL_FILTER_ERROR(1129, "General Filter Error"),
    BANK_REQUIRED_FIELDS_MISSING(1130, "Bank required fields are missing or incorrect"),
    TXN_TYPE_NOT_ALLOWED_FOR_BANK(1131, "This transaction type is not allowed for this bank"),
    AMOUNT_EXCEEDS_BANK_LIMIT(1132, "Amount exceeds bank limit"),
    GW_REQUIRED_FIELDS_MISSING(1133, "GW required fields are missing"),
    AVS_PROCESSOR_ERROR(1134, "AVS Processor Error"),
    ONE_CREDIT_PER_SALE(1135, "Only one credit per sale is allowed"),
    MANDATORY_FIELDS_MISSING(1136, "Mandatory fields are missing"),
    CREDIT_COUNT_EXCEEDED(1137, "Credit count exceeded CCC restriction"),
    INVALID_CREDIT_TYPE(1138, "Invalid Credit Type"),
    CARD_NOT_SUPPORTED_CFT(1139, "This card is not supported in the CFT Program"),
    MUST_PROCESS_IN_GW(1140, "Card must be processed in the GW System"),
    TXN_TYPE_NOT_ALLOWED(1141, "Transaction type is not allowed"),
    AVS_FIELDS_MISSING(1142, "AVS required fields are missing or incorrect"),
    COUNTRY_MISMATCH_ISO(1143, "Country does not match ISO Code"),
    MISSING_USERID_REBILL(1144, "Must provide UserID in a Rebill transaction"),
    REBILL_PROFILE_UNSUPPORTED(1145, "Your Rebill profile do not supprt this transaction type"),
    VOID_NOT_ALLOWED_CCC(1146, "Void is not allowed due to CCC restriction"),
    INVALID_ACCOUNT_NUMBER(1147, "Invalid Account Number"),
    INVALID_CHEQUE_NUMBER(1148, "Invalid Cheque Number"),
    ACCOUNT_TRANS_ID_MISMATCH(1149, "Account Number/Trans ID Mismatch"),
    USERID_TRANS_TYPE_MISMATCH(1150, "UserID/Trans Type /Trans ID Mismatch"),
    TXN_NOT_EXIST_REBILL(1151, "Transaction does not exist in the rebill system."),
    TXN_ALREADY_CANCELED(1152, "Transaction was already canceled"),
    INVALID_BANK_CODE_DIGITS(1153, "Invalid Bank Code(Digits Count)"),
    INVALID_BANK_CODE_ALPHA(1154, "Invalid Bank Code (Alpha Numeric)"),
    THREE_D_RELATED_TXN_MISSING(1155, "3D Related transaction is missing or incorrect"),
    DEBIT_CARD_FIELDS_MISSING(1156, "Debit card required fields are missing or incorrect"),
    NO_UPDATE_PARAMS(1157, "No update parameters were supplied"),
    THREE_D_PARES_INCORRECT(1158, "3D PaRes value is incorrect"),
    PAYPAL_ALREADY_REGISTERED(1158, "PayPal account is already registered by another user"),
    STATE_MISMATCH_ISO(1159, "State does not match ISO Code"),
    USER_ALREADY_REGISTERED_DIFFERENT_EMAIL(1159, "The user already registered with a different Payer email"),
    INVALID_BANK_CODE_CHECKSUM(1160, "Invalid Bank Code (Checksum Digit)"),
    SINGLE_ACCOUNT_VALIDATION_FAILED(1160, "Single account validation failed"),
    CVV2_3_DIGITS_ONLY(1161, "This Bank allows only 3 digits in CVV2"),
    AGE_VERIFICATION_FAILED(1162, "Age verification Failed"),
    MISSING_CARD_TOKEN_ACCOUNT(1163, "Transaction must contain a Card/Token/Account"),
    INVALID_TOKEN(1164, "Invalid Token"),
    TOKEN_MISMATCH(1165, "Token Mismatch"),
    INVALID_EMAIL(1166, "Invalid Email address"),
    TRANSACTION_ALREADY_SETTLED(1167, "Transaction already settled"),
    MISSING_EXTERNAL_MPI_PARAMS(1167, "Missing external MPI parameters"),
    TRANSACTION_ALREADY_VOIDED(1168, "Transaction already voided"),
    INVALID_RESPONSE_FORMAT(1169, "sg_ResponseFormat field is not valid"),
    INVALID_VERSION_FIELD(1170, "Version field is missing or incorrect"),
    INVALID_ISSUING_COUNTRY(1171, "Issuing Country is invalid"),
    PHONE_MISSING_OR_INVALID(1172, "Phone is missing or format error"),
    CHEQUE_NUMBER_MISSING(1173, "Check number is missing or incorrect"),
    BIRTH_DATE_ERROR(1174, "Birth date format error"),
    ZIP_CODE_ERROR(1175, "Zip code format error"),
    CANNOT_VOID_AUTH(1176, "Cannot void an auth transaction"),
    CANNOT_VOID_CREDIT(1177, "Cannot void a credit transaction"),
    CANNOT_VOID_VOID(1178, "Cannot void a void transaction"),
    CANNOT_PERFORM_VOID(1179, "Cannot perform this void"),
    INVALID_START_DATE(1180, "Invalid start date"),
    MERCHANT_NAME_TOO_LONG(1181, "Merchant Name is too long (>25)"),
    MUST_SEND_AS_3DSECURE(1182, "Transaction must be sent as 3Dsecure"),
    ACCOUNT_NOT_3D_ENABLED(1183, "Account is not 3D enabled"),
    TRANSACTION_3D_STATUS_INCORRECT(1184, "Transaction 3D status is incorrect"),
    RELATED_TX_MUST_BE_AUTH3D(1185, "Related transaction must be Auth3D, APPROVED, same 3DS version and same merchant"),
    RELATED_TX_MUST_BE_3D_AUTHENTICATED(1186, "Related transaction must be 3D authenticated"),
    COUNTRY_NOT_SUPPORTED_CFT(1187, "Country does not support the CFT program"),
    INVALID_TOKEN_ID(1188, "Invalid token id"),
    RISK_PROCESSOR_ERROR(1190, "Risk processor error"),
    RISKONLY_VERSION_NOT_SUPPORTED(1191, "RiskOnly is supported from version 4.0.0 and above"),
    AGV_PROCESSOR_ERROR(1192, "AGV processor error"),
    AGVONLY_VERSION_NOT_SUPPORTED(1193, "AGVOnly is supported from version 4.0.1 and above"),
    AGE_VERIFICATION_MISMATCH(1194, "Age verification mismatch"),
    REQUESTED_ACQUIRER_UNRECOGNIZED(1195, "Requested acquirer is unrecognized"),
    SALE_NOT_PROCESSED_ACQUIRER(1196, "sale transaction isn't processed on acquirer side yet"),
    INPUT_DATA_NOT_SUFFICIENT(1197, "Input data is not sufficient"),
    CC_DETAILS_NOT_ALLOWED_FOR_PAYMENT_METHOD(1198, "Credit card details are not allowed for the given Payment Method"),
    ENVOY_PAYOUT_REQUIRES_CREDIT_TYPE1(1199, "Envoy payout transaction requires credit transaction of type 1"),
    INVALID_ISSUING_BANK_COUNTRY_CODE(1200, "invalid issuing bank country code"),
    INVALID_AMOUNT(1201, "Invalid Amount"),
    INVALID_CURRENCY(1202, "Invalid Currency"),
    IBAN_NOT_MATCH_COUNTRY_CODE(1203, "IBAN does not match country code"),
    PAYMENT_METHOD_NOT_SUPPORTED(1204, "Payment method is not supported"),
    APM_RISK_PROCESSOR_ERROR(1205, "APM risk processor error"),
    SETTLE_AMOUNT_EXCEEDS_TOTAL_CHARGES(1206, "Settle amount exceeds total charges"),
    CANNOT_PERFORM_CREDIT(1207, "Cannot perform this credit"),
    CONVERTED_TX_NOT_HANDLED(1208, "Converted transaction cannot be handled, please use alternative interfaces"),
    CLIENT_NOT_ALLOWED_PARTIAL_APPROVAL(1209, "Client is not allowed for Partial Approval"),
    NAMEONCARD_MISSING(1210, "NameOnCard is missing"),
    INVALID_FINALIZATION_URL(1214, "Invalid FinalizationURL"),
    EXPIRED_TOKEN(1220, "Expired Token"),
    INVALID_OR_MISSING_PFSUBMERCHANTID(1230, "Invalid or missing PFSubMerchantId input parameter"),
    INVALID_OR_MISSING_MERCHANTNAME(1231, "Invalid or missing MerchantName input parameter"),
    INVALID_OR_MISSING_PFSUBMERCHANTCOUNTRY(1232, "Invalid or missing PFSubMerchantCountry input parameter"),
    INVALID_OR_MISSING_PFSUBMERCHANTCITY(1233, "Invalid or missing PFSubMerchantCity input parameter"),
    ONE_YEAR_PASSED_PAYOUT_DECLINED(1265, "One year passed since last sale, Payout declined"),
    SUBMETHOD_NOT_SUPPORTED(1266, "Submethod not supported"),
    CARD_NOT_SUPPORTED_VISA_DIRECT_OCT(1267, "This card is not supported in the Visa Direct OCT program."),
    TOKEN_INACTIVE(1268, "Token is inactive"),
    CANNOT_GET_CRYPTOGRAM(1269, "Cannot get cryptogram"),
    CLIENT_NOT_CONFIGURED_ACCOUNT_UPDATE(1270, "The client is not configured to account update"),
    SG_TRANSACTION_NOT_VALID(1271, "sg_transaction must be of type InitAuth3D, Approved and the same merchant"),
    CARD_NUMBER_MUST_BE_EQUAL_3DS_FLOW(1272, "Card number must be equal for all transaction in a specific 3DS flow"),
    CARD_CURRENCY_AMOUNT_MUST_BE_EQUAL_3DS_FLOW(1273, "Card number, Currency and Amount must be equal in a specific 3DS flow"),
    REQUESTED_AUTH3D2_NOT_SUPPORTED_CARD(1274, "Requested Auth3D 2.0 but card number is not supported with 3DS 2.0"),
    INITAUTH3D_ALREADY_USED(1275, "initAuth3D represented by sg_transactionId was already used in another 3D flow"),
    AUTHENTICATION_TIMEOUT(1276, "authentication request could not be completed – timeout, please try again later"),
    DS_RESPONDED_ERROR(1277, "DS responded with an error, please verify request and try again"),
    AUTHENTICATION_EXPIRED(1278, "Authentication is expired, new InitAuth3d is required"),
    RELATED_TX_ALREADY_USED_FOR_SALE(1279, "3D related transaction was already used for Sale/Auth"),
    MISSING_THREEDS_METHOD_NOTIFICATION_URL(1280, "Mandatory field is missing: sg_threeDSMethodNotificationURL"),
    AUTHENTICATION_NOT_COMPLETED(1281, "Authentication has not completed"),
    AUTHENTICATION_FAILED(1282, "Authentication failed"),
    MISSING_THREEDSPLATFORMTYPE(1283, "Required field sg_ThreeDSPlatformType is missing or invalid"),
    INVALID_EXTERNAL_MPI_PARAMS(1284, "Invalid external MPI parameters format"),
    EXCEEDING_REFUND_TIMEFRAME(1285, "Exceeding refund time frame"),
    VOID_NOT_SUPPORTED_FOR_RELATED_TX(1288, "Void is not supported for the related transaction type in current processor"),
    ISSUER_DATA_NOT_AVAILABLE(1289, "Issuer data is not available, please try again later"),
    NEXTACTION_DOCHALLENGE_INVALID(1290, "NextAction is DoChallenge but challenge result is not allowing Sale/Auth"),
    NEXTACTION_STOP(1292, "NextAction is Stop, no further transaction should be sent"),
    TEMPORARY_3DS_TECHNICAL_ERROR(1293, "Temporary Technical Malfunction in 3DS 2.0, Please Retry"),
    OCT_CANNOT_EXCEED_10000_EUROS(1295, "OCT Cannot exceed 10,000 Euros cross border in Azerbaijan, Moldova, Ukraine"),
    NON_DOMESTIC_OCT_NOT_ALLOWED(1296, "Non Domestic OCT is not allowed in the current issuer or merchant country"),
    ACQUIRER_REFNO_AUTHCODE_DUPLICATION(1297, "Acquirer Reference Number and Authcode Duplication"),
    EXCEEDED_RETRY_LIMIT(1300, "Exceeded retry limit, issuer will not approve same amount."),
    CLIENT_NOT_ALLOWED_CHANNEL(1500, "Client Is Not Allowed To Use This Channel"),
    CLIENT_NOT_ALLOWED_SUPPRESS_AUTH(1501, "Client Is Not Allowed To Use Suppress Auth"),
    AUTO_REVERSAL_PARAMS_MISSING(1550, "Not all the auto reversal parameters were sent in the request"),
    CLIENT_NOT_PERMITTED_AUTO_REVERSAL(1551, "Client is not permitted to use auto reversal functionality"),
    INPUT_PARAMETER_TYPE_INCORRECT(1552, "Input parameter data type incorrect"),
    AUTO_REVERSAL_CURRENCY_MISMATCH(1553, "Currency of auto reversal does not match the currency of the settle"),
    AUTO_REVERSAL_AMOUNT_MISMATCH(1554, "Amount of auto reversal does not match the amount of the settle and auth"),
    AUTO_REVERSAL_MULTIPLE_SETTLE_NOT_ALLOWED(1555, "Auto Reversal Cannot be Allowed with Multiple Settle"),
    AUTO_REVERSAL_AMOUNT_SHOULD_MATCH_ORIGINAL(1556, "Settle amount plus AutoReversal Amount should be equal to Original Auth"),
    AUTO_REVERSAL_CURRENCY_NOT_MATCH(1557, "Original currency does not match auto reversal currency"),
    AUTO_REVERSAL_INPUT_PARAMS_INCORRECT(1558, "Incorrect Auto-Reversal Input Parameters"),
    CANNOT_VOID_AUTH_ALREADY_SETTLED(1559, "Cannot void auth, transaction has already been settled"),
    NOT_ALLOWED_PROCESS_AUTH_TYPE(1560, "Not Allowed to Process this Auth Type"),
    REQUESTED_ACQUIRER_UNAVAILABLE(2001, "The requested acquirer bank is temporarily unavailable"),
    APMRISK_DISABLED(2002, "ApmRisk is disabled"),
    EXTERNAL_MPI_NOT_SUPPORTED(2025, "External MPI not supported for this acquirer"),
    INVALID_EXTERNAL_TOKEN_PROVIDER(2030, "Invalid external token provider"),
    INVALID_INTERVAL_SALE_REVERSAL(3001, "Invalid Interval for sale reversal"),
    INVALID_INTERVAL_REFUND_REVERSAL(3002, "Invalid Interval for refund reversal"),
    INVALID_INTERVAL_OCT_REVERSAL(3003, "Invalid Interval for OCT reversal"),
    TRANSACTION_ALREADY_REVERSED(3004, "Transaction has already been reversed"),
    TRANSACTION_NOT_APPROVED(3005, "Transaction is not approved"),
    TRANSACTION_ID_NOT_EXIST(3306, "TransactionID either wrong or not exist"),
    INSTALLMENTS_NOT_ALLOWED(3507, "Installments are not allowed."),
    INVALID_NUMBER_OF_INSTALLMENTS(3508, "Number of instalments must be equal to 0 or greater"),
    MISSING_INSTALLMENT_DETAILS(3509, "Missing firstInstallment, periodicalInstallment or numberOfInstallments."),
    SAVED_PAYMENT_OPTION_NO_LONGER_VALID(10012, "Saved payment option no longer valid"),
    CANNOT_REGISTER_PAYMENT_OPTION_AT_APM(10013, "Cannot register payment option at APM"),
    APM_AUTHENTICATION_ERROR(10014, "APM authentication error"),
    INVALID_MONEY_SEND_PARAMETER(10025, "Invalid or missing parameter for MoneySend transaction"),
    TWO_PHASE_NOT_SUPPORTED_IN_VISA_DIRECT_AFT(10026, "Two-phase Auth-Settle process is not supported in the Visa Direct AFT program"),
    NON_DOMESTIC_AFT_NOT_ALLOWED(10027, "Non Domestic AFT is not allowed in the current issuer or merchant country"),
    CARD_PRESENT_NOT_SUPPORTED_IN_VISA_DIRECT_AFT(10028, "Card-present transaction is not supported in the Visa Direct AFT program"),
    INSTALLMENTS_PROGRAM_INVALID(10029, "Installments program is missing or invalid."),
    INVALID_INSTALLMENT_NUMBER(10030, "Number of installments must be valid and greater than 0."),
    SENDER_NAME_REQUIRED_FOR_CROSSBORDER(10031, "SenderName required for Crossborder transaction"),
    INVALID_INTERVAL_FOR_AFT_CREDIT_ADJUSTMENT(10034, "Invalid interval for AFT Credit Adjustment"),
    MISSING_RECIPIENT_INFO(10035, "Missing RecipientCardNumber or RecipientToken value"),
    BATCH_NUMBER_ALREADY_CLOSED(10036, "Batch Number of the transaction was marked as closed in the last 60 days"),
    CLIENT_NOT_CONFIGURED_FOR_EXTERNAL_AUTH(10037, "The client is not configured to External Authorization"),
    INVALID_CASCADE_TO_CREDIT_PARAM(10038, "sg_CascadeToCredit parameter is invalid"),
    AMOUNT_EXCEEDS_UNREFERENCED_REFUND_LIMIT(10040, "Amount exceeds unreferenced refund Limit"),
    MISSING_TAX_AMOUNT_BASE(10041, "Missing mandatory field: \"sg_TaxAmountBase\""),
    MISSING_PERSONAL_ID(10042, "Missing mandatory field: \"sg_personalID\""),
    INSTALLMENTS_NUMBER_EXCEEDED(10043, "Installments number exceeded the max allowed number, max number is 99"),
    SETTLE_AMOUNT_EXCEEDS_AUTH_THRESHOLDS(10044, "Settle amount exceeds Authorization thresholds"),
    INVALID_BATCH_START_DATE(10046, "sg_BatchStartGMT is invalid (Past date)"),
    BATCH_NUMBER_ALREADY_CLOSED_RECENTLY(10047, "Batch Number of the transaction was marked as closed in the last 60 days"),
    DEBIT_OR_PREPAID_NOT_ALLOWED_IN_INSTALLMENT(10048, "Debit or Prepaid card types can not be processed in installment transaction."),
    VISA_COLOMBIA_DOMESTIC_MUST_BE_COP(10049, "Visa Colombian domestic transaction should be sent in COP currency only"),
    MISSING_FIRST_NAME(10050, "Missing Mandatory field : sg_FirstName"),
    MISSING_LAST_NAME(10051, "Missing Mandatory field : sg_LastName"),
    MISSING_ADDRESS_FOR_CROSSBORDER(10052, "Address is required for Crossborder transaction"),
    MISSING_CITY_FOR_CROSSBORDER(10053, "City is required for Crossborder transaction"),
    MISSING_FIRST_NAME_FOR_SOUTH_AFRICA(10054, "AFT auth - Missing Identification values for South Africa - First Name"),
    VOID_NOT_ALLOWED_ON_FAST_FUNDS(10055, "Void not allowed on fast funds payouts"),
    MISSING_ADDRESS_FOR_CROSSBORDER_ALT(10056, "Address is required for Cross-Border transaction"),
    MISSING_CITY_FOR_CROSSBORDER_ALT(10057, "City is required for Cross-Border transaction"),
    MISSING_CARDHOLDER_NAME_FOR_SOUTH_AFRICA(10058, "NameOnCard/FirstName + LastName is required for Cross-Border of South-African transaction"),
    MISSING_PHONE_OR_EMAIL_FOR_BRAZIL(10059, "AFT auth - Missing Identification values for Brazil - Phone or Email"),
    CARD_BRAND_NOT_ALLOWED(10060, "Merchant Restriction configuration - Card Brand is not allowed to be process"),
    MISSING_COUNTRY_FOR_CROSSBORDER(10061, "Country is required for Cross-Border transaction"),
    INVALID_BAI_VALUE(10062, "Invalid BAI value"),
    MERCHANT_NOT_APPROVED_FOR_CROSSBORDER_AFT(10065, "Merchant is not approved for Cross-border AFT"),
    MISSING_ADDRESS(10066, "Mandatory input param sg_Address is missing"),
    MISSING_CITY(10067, "Mandatory input param sg_City is missing"),
    MISSING_STATE(10068, "Mandatory input param sg_state is missing"),
    MISSING_ZIP(10069, "Mandatory input param sg_zip is missing"),
    MISSING_BATCH_NUMBER(10070, "Missing mandatory fields: \"sg_BatchNumber\""),
    MISSING_BATCH_START_GMT(10071, "Missing mandatory fields: \"sg_BatchStartGMT\""),
    COLOMBIA_DOMESTIC_TRANSACTION_NOT_ALLOWED(10072, "Colombia domestic transaction is not allowed"),
    STATE_NOT_MATCH_ISO_CODE(10073, "State does not match ISO Code"),
    AMEX_NOT_SUPPORTS_3D_AND_APPLEPAY(10074, "AMEX doesn't support both 3D and External Token Provider (Apple Pay) transaction"),
    PAYMENTEZ_NOT_SUPPORTS_3D_AND_EXTERNAL_TOKEN(10075, "Paymentez doesn't support both 3D and External Token Provider transaction"),
    UnknownError(0, "Unknown exception");


    private final int code;
    private final String description;

    PaymentGWErrorCode(int code, String description) {
        this.code = code;
        this.description = description;
    }

    public static String getDescriptionFromCode(int code) {
        for (PaymentGWErrorCode e : values()) {
            if (e.code == code) {
                return e.getDescription();
            }
        }
        return UnknownError.getDescription();
    }

}
