package com.games.payment.domain;

import com.baomidou.mybatisplus.annotation.*;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.io.Serializable;
import java.util.Date;

/**
 * Thunes 首选银行配置实体
 *
 * @author System
 * @date 2025-01-09
 */
@Data
@EqualsAndHashCode(callSuper = false)
@TableName("thunes_preferred_bank")
public class ThunesPreferredBank implements Serializable {

    private static final long serialVersionUID = 1L;

    /** 主键ID */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /** 国家代码 */
    @TableField("country_code")
    private String countryCode;

    /** 银行名称 */
    @TableField("bank_name")
    private String bankName;

    /** 银行关键词（用于匹配） */
    @TableField("bank_keyword")
    private String bankKeyword;

    /** 优先级（数字越小优先级越高） */
    @TableField("priority")
    private Integer priority;

    /** 对应的 Thunes Payer ID */
    @TableField("payer_id")
    private Long payerId;

    /** 对应的 Thunes Payer 名称 */
    @TableField("payer_name")
    private String payerName;

    /** 是否启用（1-启用，0-禁用） */
    @TableField("is_active")
    private Boolean isActive;

    /** 是否自动生成（1-自动，0-手动配置） */
    @TableField("is_auto_generated")
    private Boolean isAutoGenerated;

    /** 创建时间 */
    @TableField(value = "created_at", fill = FieldFill.INSERT)
    private Date createdAt;

    /** 更新时间 */
    @TableField(value = "updated_at", fill = FieldFill.INSERT_UPDATE)
    private Date updatedAt;
}