package com.games.thunes;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.games.payment.domain.ThunesPreferredBank;
import com.games.payment.domain.ThunesSupportedCountry;
import com.games.payment.service.IThunesPreferredBankService;
import com.games.payment.service.IThunesSupportedCountryService;
import com.games.thunes.dto.PayerDto;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.*;
import java.util.stream.Collectors;

/**
 * Thunes 配置事务服务
 * 专门处理需要事务的配置同步操作，避免自调用问题
 *
 * @author System
 * @date 2025-01-12
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class ThunesConfigTransactionService {

    private final ThunesApiService thunesApiService;
    private final IThunesSupportedCountryService supportedCountryService;
    private final IThunesPreferredBankService preferredBankService;

    /**
     * 同步国家货币配置（事务方法）
     */
    @Transactional(rollbackFor = Exception.class)
    public void syncCountryCurrencyConfig() {
        log.info("开始同步国家货币配置");

        // 获取所有支付方信息
        List<PayerDto> allPayers = thunesApiService.getPayers(null, null);

        // 统计每个国家货币的支付方数量
        Map<String, Map<String, Integer>> countryStats = new HashMap<>();
        for (PayerDto payer : allPayers) {
            String countryCode = payer.getCountryIsoCode();
            String currency = payer.getCurrency();

            countryStats.computeIfAbsent(countryCode, k -> new HashMap<>())
                    .merge(currency, 1, Integer::sum);
        }

        // 更新数据库
        int totalRecords = 0;
        int successRecords = 0;

        for (Map.Entry<String, Map<String, Integer>> countryEntry : countryStats.entrySet()) {
            String countryCode = countryEntry.getKey();

            for (Map.Entry<String, Integer> currencyEntry : countryEntry.getValue().entrySet()) {
                String currency = currencyEntry.getKey();
                Integer payerCount = currencyEntry.getValue();

                totalRecords++;

                try {
                    // 查找现有记录
                    LambdaQueryWrapper<ThunesSupportedCountry> wrapper = new LambdaQueryWrapper<>();
                    wrapper.eq(ThunesSupportedCountry::getCountryCode, countryCode)
                            .eq(ThunesSupportedCountry::getCurrency, currency);

                    ThunesSupportedCountry existing = supportedCountryService.getOne(wrapper);

                    if (existing != null) {
                        // 更新现有记录
                        existing.setPayerCount(payerCount);
                        existing.setIsActive(true);
                        supportedCountryService.updateById(existing);
                    } else {
                        // 创建新记录
                        ThunesSupportedCountry newRecord = new ThunesSupportedCountry();
                        newRecord.setCountryCode(countryCode);
                        newRecord.setCurrency(currency);
                        newRecord.setPayerCount(payerCount);
                        newRecord.setIsActive(true);
                        supportedCountryService.save(newRecord);
                    }

                    successRecords++;
                } catch (Exception e) {
                    log.error("同步国家货币配置失败 - 国家: {}, 货币: {}", countryCode, currency, e);
                }
            }
        }

        log.info("国家货币配置同步完成 - 总数: {}, 成功: {}, 失败: {}",
                totalRecords, successRecords, totalRecords - successRecords);
    }

    /**
     * 同步首选银行配置（事务方法）
     */
    @Transactional(rollbackFor = Exception.class)
    public void syncPreferredBankConfig() {
        log.info("开始同步首选银行配置");

        // 获取所有支付方信息
        List<PayerDto> allPayers = thunesApiService.getPayers(null, null);

        // 按国家分组
        Map<String, List<PayerDto>> payersByCountry = allPayers.stream()
                .collect(Collectors.groupingBy(PayerDto::getCountryIsoCode));

        int totalRecords = 0;
        int successRecords = 0;

        for (Map.Entry<String, List<PayerDto>> entry : payersByCountry.entrySet()) {
            String countryCode = entry.getKey();
            List<PayerDto> countryPayers = entry.getValue();

            // 获取现有的手动配置（优先级更高，不覆盖）
            LambdaQueryWrapper<ThunesPreferredBank> manualWrapper = new LambdaQueryWrapper<>();
            manualWrapper.eq(ThunesPreferredBank::getCountryCode, countryCode)
                    .eq(ThunesPreferredBank::getIsAutoGenerated, false);
            List<ThunesPreferredBank> manualBanks = preferredBankService.list(manualWrapper);

            // 更新手动配置的 Payer 信息
            for (ThunesPreferredBank manualBank : manualBanks) {
                totalRecords++;
                try {
                    // 查找匹配的 Payer
                    PayerDto matchedPayer = findMatchingPayer(countryPayers, manualBank.getBankKeyword());
                    if (matchedPayer != null) {
                        manualBank.setPayerId(matchedPayer.getId());
                        manualBank.setPayerName(matchedPayer.getName());
                        preferredBankService.updateById(manualBank);
                    }
                    successRecords++;
                } catch (Exception e) {
                    log.error("更新手动配置银行失败 - 国家: {}, 银行: {}", countryCode, manualBank.getBankName(), e);
                }
            }

            // 为没有手动配置的国家生成自动配置
            if (manualBanks.isEmpty()) {
                List<String> autoBanks = buildCountrySpecificPreferredBanks(countryCode, countryPayers);

                // 删除旧的自动生成配置
                LambdaQueryWrapper<ThunesPreferredBank> autoWrapper = new LambdaQueryWrapper<>();
                autoWrapper.eq(ThunesPreferredBank::getCountryCode, countryCode)
                        .eq(ThunesPreferredBank::getIsAutoGenerated, true);
                preferredBankService.remove(autoWrapper);

                // 创建新的自动配置
                for (int i = 0; i < autoBanks.size(); i++) {
                    totalRecords++;
                    try {
                        String bankName = autoBanks.get(i);
                        PayerDto matchedPayer = findMatchingPayer(countryPayers, bankName);

                        if (matchedPayer != null) {
                            ThunesPreferredBank autoBank = new ThunesPreferredBank();
                            autoBank.setCountryCode(countryCode);
                            autoBank.setBankName(bankName);
                            autoBank.setBankKeyword(bankName.toUpperCase());
                            autoBank.setPriority(100 + i); // 自动配置优先级较低
                            autoBank.setPayerId(matchedPayer.getId());
                            autoBank.setPayerName(matchedPayer.getName());
                            autoBank.setIsActive(true);
                            autoBank.setIsAutoGenerated(true);

                            preferredBankService.save(autoBank);
                            successRecords++;
                        }
                    } catch (Exception e) {
                        log.error("创建自动配置银行失败 - 国家: {}, 银行: {}", countryCode, autoBanks.get(i), e);
                    }
                }
            }
        }

        log.info("首选银行配置同步完成 - 总数: {}, 成功: {}, 失败: {}",
                totalRecords, successRecords, totalRecords - successRecords);
    }

    /**
     * 查找匹配的 Payer
     */
    private PayerDto findMatchingPayer(List<PayerDto> payers, String keyword) {
        return payers.stream()
                .filter(payer -> payer.getName().toUpperCase().contains(keyword.toUpperCase()))
                .findFirst()
                .orElse(null);
    }

    /**
     * 构建国家的首选银行列表（完全基于数据库配置和智能匹配，无硬编码逻辑）
     */
    private List<String> buildCountrySpecificPreferredBanks(String countryCode, List<PayerDto> payers) {
        List<String> preferredBanks = new ArrayList<>();

        // 1. 首先尝试基于现有手动配置进行匹配
        LambdaQueryWrapper<ThunesPreferredBank> manualWrapper = new LambdaQueryWrapper<>();
        manualWrapper.eq(ThunesPreferredBank::getCountryCode, countryCode)
                .eq(ThunesPreferredBank::getIsAutoGenerated, false)
                .eq(ThunesPreferredBank::getIsActive, true)
                .orderByAsc(ThunesPreferredBank::getPriority);

        List<ThunesPreferredBank> manualBanks = preferredBankService.list(manualWrapper);

        // 如果有手动配置，优先使用手动配置的关键词进行匹配
        for (ThunesPreferredBank manualBank : manualBanks) {
            PayerDto matchedPayer = findMatchingPayer(payers, manualBank.getBankKeyword());
            if (matchedPayer != null && !preferredBanks.contains(matchedPayer.getName())) {
                preferredBanks.add(matchedPayer.getName());
            }
        }

        // 2. 如果手动配置匹配的银行不足，使用智能匹配补充
        if (preferredBanks.size() < 3) {
            List<String> smartMatched = smartMatchBanks(payers, preferredBanks);
            preferredBanks.addAll(smartMatched);
        }

        // 3. 如果仍然不足，选择剩余的支付方（按名称排序，确保结果稳定）
        if (preferredBanks.size() < 3) {
            List<String> remaining = payers.stream()
                    .map(PayerDto::getName)
                    .filter(name -> !preferredBanks.contains(name))
                    .sorted() // 按名称排序，确保结果稳定
                    .limit(3 - preferredBanks.size())
                    .collect(Collectors.toList());
            preferredBanks.addAll(remaining);
        }

        return preferredBanks;
    }

    /**
     * 智能匹配银行（基于常见银行关键词和支付方名称特征）
     */
    private List<String> smartMatchBanks(List<PayerDto> payers, List<String> excludeList) {
        List<String> smartMatched = new ArrayList<>();

        // 常见的银行关键词（按重要性排序）
        String[] commonBankKeywords = {
                // 通用银行关键词
                "BANK", "BANCO", "BANQUE", "BANCA", "BANKING",
                // 银行类型关键词
                "NATIONAL", "CENTRAL", "COMMERCIAL", "INTERNATIONAL", "FEDERAL",
                "CREDIT", "SAVINGS", "TRUST", "UNION", "COOPERATIVE",
                // 知名国际银行
                "HSBC", "SANTANDER", "BBVA", "BNP", "DEUTSCHE", "CITIBANK",
                "STANDARD", "BARCLAYS", "LLOYDS", "CHASE", "WELLS"
        };

        // 按关键词重要性匹配，避免重复
        Set<String> usedPayerNames = new HashSet<>(excludeList);

        for (String keyword : commonBankKeywords) {
            if (smartMatched.size() >= 3)
                break;

            // 查找包含该关键词且未被使用的支付方
            PayerDto matchedPayer = payers.stream()
                    .filter(payer -> payer.getName().toUpperCase().contains(keyword))
                    .filter(payer -> !usedPayerNames.contains(payer.getName()))
                    .findFirst()
                    .orElse(null);

            if (matchedPayer != null) {
                smartMatched.add(matchedPayer.getName());
                usedPayerNames.add(matchedPayer.getName());
            }
        }

        return smartMatched;
    }
}