package com.games.thunes;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.games.payment.domain.ThunesPreferredBank;
import com.games.payment.domain.ThunesSupportedCountry;
import com.games.payment.service.IThunesPreferredBankService;
import com.games.payment.service.IThunesSupportedCountryService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.*;
import java.util.stream.Collectors;

/**
 * Thunes 配置服务（基于数据库存储）
 * 负责管理支持的国家、首选银行等配置信息
 *
 * @author System
 * @date 2025-01-09
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class ThunesConfigService {

    private final IThunesSupportedCountryService supportedCountryService;
    private final IThunesPreferredBankService preferredBankService;
    private final ThunesConfigTransactionService transactionService;

    /**
     * 检查是否支持指定的国家和货币
     */
    public boolean isSupportedCountryAndCurrency(String countryCode, String currency) {
        LambdaQueryWrapper<ThunesSupportedCountry> wrapper = new LambdaQueryWrapper<>();
        wrapper.eq(ThunesSupportedCountry::getCountryCode, countryCode)
                .eq(ThunesSupportedCountry::getCurrency, currency)
                .eq(ThunesSupportedCountry::getIsActive, true);

        return supportedCountryService.count(wrapper) > 0;
    }

    /**
     * 获取支持的国家列表
     */
    public Set<String> getSupportedCountries() {
        LambdaQueryWrapper<ThunesSupportedCountry> wrapper = new LambdaQueryWrapper<>();
        wrapper.eq(ThunesSupportedCountry::getIsActive, true)
                .select(ThunesSupportedCountry::getCountryCode);

        return supportedCountryService.list(wrapper).stream()
                .map(ThunesSupportedCountry::getCountryCode)
                .collect(Collectors.toSet());
    }

    /**
     * 获取指定国家支持的货币列表
     */
    public Set<String> getSupportedCurrencies(String countryCode) {
        LambdaQueryWrapper<ThunesSupportedCountry> wrapper = new LambdaQueryWrapper<>();
        wrapper.eq(ThunesSupportedCountry::getCountryCode, countryCode)
                .eq(ThunesSupportedCountry::getIsActive, true)
                .select(ThunesSupportedCountry::getCurrency);

        return supportedCountryService.list(wrapper).stream()
                .map(ThunesSupportedCountry::getCurrency)
                .collect(Collectors.toSet());
    }

    /**
     * 获取指定国家的首选银行列表
     */
    public List<String> getPreferredBanks(String countryCode) {
        LambdaQueryWrapper<ThunesPreferredBank> wrapper = new LambdaQueryWrapper<>();
        wrapper.eq(ThunesPreferredBank::getCountryCode, countryCode)
                .eq(ThunesPreferredBank::getIsActive, true)
                .orderByAsc(ThunesPreferredBank::getPriority)
                .select(ThunesPreferredBank::getBankName);

        return preferredBankService.list(wrapper).stream()
                .map(ThunesPreferredBank::getBankName)
                .collect(Collectors.toList());
    }

    /**
     * 手动同步所有配置
     */
    public void manualSyncAllConfig() {
        log.info("开始手动同步 Thunes 配置");

        transactionService.syncCountryCurrencyConfig();
        transactionService.syncPreferredBankConfig();

        log.info("手动同步 Thunes 配置完成");
    }

    /**
     * 获取同步统计信息
     */
    public Map<String, Object> getSyncStats() {
        Map<String, Object> stats = new HashMap<>();

        // 国家货币统计
        long countryCurrencyCount = supportedCountryService.count();
        stats.put("supportedCountryCurrencyCount", countryCurrencyCount);

        // 首选银行统计
        long preferredBankCount = preferredBankService.count();
        stats.put("preferredBankCount", preferredBankCount);

        // 手动配置银行统计
        LambdaQueryWrapper<ThunesPreferredBank> manualWrapper = new LambdaQueryWrapper<>();
        manualWrapper.eq(ThunesPreferredBank::getIsAutoGenerated, false);
        long manualBankCount = preferredBankService.count(manualWrapper);
        stats.put("manualBankCount", manualBankCount);

        // 自动生成银行统计
        LambdaQueryWrapper<ThunesPreferredBank> autoWrapper = new LambdaQueryWrapper<>();
        autoWrapper.eq(ThunesPreferredBank::getIsAutoGenerated, true);
        long autoBankCount = preferredBankService.count(autoWrapper);
        stats.put("autoBankCount", autoBankCount);

        return stats;
    }
}